/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "musicplayers",
  "description": "a music player by vuepress",
  "base": "/vuepress-plugin-awesome-musicplayer/",
  "headTags": [],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-5508b665",
      "path": "/",
      "lastUpdated": "12/23/2021, 6:41:58 PM",
      "lastUpdatedTimestamp": 1640256118000
    }
  ],
  "themeConfig": {
    "editLinks": true,
    "docsDir": "docs",
    "editLinkText": "Edit this page on GitHub",
    "lastUpdated": "Last Updated"
  }
}